# Generated by Django 4.2.11 on 2026-05-09 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_records', '0001_initial'),
        ('patients', '0001_initial'),
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('emergency', 'Emergency'), ('warning', 'Warning')], max_length=15)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='health_records.healthrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.patientprofile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to='doctors.doctorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
