# Generated by Django 4.2.11 on 2026-05-09 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse_rate', models.FloatField(help_text='Heart rate in BPM')),
                ('spo2', models.FloatField(help_text='Blood oxygen saturation percentage')),
                ('temperature', models.FloatField(help_text='Body temperature in Fahrenheit')),
                ('status', models.CharField(choices=[('green', 'Green — Healthy'), ('yellow', 'Yellow — Warning'), ('red', 'Red — Emergency')], max_length=10)),
                ('analysis_note', models.TextField(help_text='Detailed analysis from the rule engine')),
                ('recommendations', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
